plugins:
  - jekyll-paginate-v2
soc: <li><a href="#"><i class="fa fa-vk"></i></a></li> <li><a href="#"><i
  class="fa fa-instagram"></i></a></li> <li><a href="#"><i class="fa
  fa-youtube"></i></a></li> <li><a href="#"><i class="fa
  fa-pinterest-p"></i></a></li> <li><a href="#"><i class="fa
  fa-rss"></i></a></li>
name: Blessing
title: Новые сумки
thumbnail: /images/screenshot_1.jpg
category_dir: blog
url: http://blessingflow.ru
desc: Новые сумки доступны УРААА
imagehome: img/blessing.jpg
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - js/common.js
  - npm-debug.log
  - "**/Thumbs.db"
  - libs
  - sass
  - "**/*.DS_Store"
themecolor: "#202225"
pagination:
  enabled: true
  per_page: 9
  title: :title - Страница :num
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
description: Информационный ресурс, где публикуются новости бренда Blessing, а
  также затрагивает многие новости из Fasion-индустрии
baseurl: /
