backend:
  name: github
  repo: FIRLY7971/blessingflow
  branch: main

media_folder: "images"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_config.yml"
        fields:
          - label: "Posts"
            name: "posts"
            folder: "_posts"
            create: true
            fields:
              - label: "Layout"
                name: "layout"
                widget: "hidden"
                default: "post"
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "desc"
                widget: "string"
              - label: "Categories"
                name: "cat"
                widget: "string"
              - label: "Thumbnail image"
                name: "thumbnail"
                widget: "image"
